log_level = "warn"
outputs = "All"
position = "Top"

[modules]
left = [ "Workspaces", "MediaPlayer" ]
center = [ "Clock" ]
right = [ "KeyboardLayout", "Privacy", "Settings" ]

[workspaces]
visibility_mode = "MonitorSpecific"
enable_workspace_filling = true

[clock]
format = "%a %d %b %R"

[media_player]
max_title_length = 100

[settings]
lock_cmd = "hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
bluetooth_more_cmd = "blueman-manager"

[appearance]
font_name = "Mononoki Nerd Font"
style = "Islands"
opacity = 1
background_color = "#fbf1f2"
primary_color = "#585062"
secondary_color = "#d8d5dd"
success_color = "#A3B367"
danger_color = "#EBB790"
text_color = "#D57E85"
workspace_colors = [ "#BB99B4", "#7297B9" ]
[appearance.menu]
opacity = 1
backdrop = 0.1
