#!/usr/bin/env bash

spaces () {
  # WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries')
  WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq --argjson num "$1" 'map(select(.monitorID == $num) | {key: .id | tostring, value: .windows}) | from_entries')
  seq $( expr $1 \* 10 + 1 ) $( expr $1 \* 10 + 6 ) | jq --argjson windows "${WORKSPACE_WINDOWS}" --slurp -Mc 'map(tostring) | map({id: ., windows: ($windows[.]//0)})'
}

spaces $1
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
  spaces $1
done
